"""Dopplium Parser - Parse Dopplium radar data formats."""

from .parse_dopplium import parse_dopplium
from .parse_dopplium_raw import (
    parse_dopplium_raw,
    BodyHeader,
    FrameHeader,
)
from .parse_dopplium_rdch import (
    parse_dopplium_rdch,
    RDChBodyHeader,
    CPIHeader,
)
from .parse_dopplium_radarcube import (
    parse_dopplium_radarcube,
    RadarCubeBodyHeader,
    get_range_axis,
    get_velocity_axis,
    get_azimuth_axis,
    get_elevation_axis,
    get_processing_info,
    has_known_angles,
    uses_fft_for_angles,
)
from .parse_dopplium_detections import (
    parse_dopplium_detections,
    DetectionsBodyHeader,
    DetectionsBatchHeader,
    filter_detections_by_range,
    filter_detections_by_velocity,
    filter_detections_by_amplitude,
    get_detection_statistics,
)
from .parse_dopplium_tracks import (
    parse_dopplium_tracks,
    TracksBodyHeader,
    TracksFrameHeader,
    filter_tracks_by_status,
    filter_tracks_by_class,
    filter_tracks_by_id,
    filter_tracks_by_lifetime,
    get_valid_coordinates,
    cartesian_to_spherical,
    spherical_to_cartesian,
    get_track_statistics,
    get_blob_statistics as get_track_blob_statistics,
    get_track_lifecycle_stats,
)
from .parse_dopplium_blobs import (
    parse_dopplium_blobs,
    BlobsBodyHeader,
    BlobsBatchHeader,
    filter_blobs_by_range,
    filter_blobs_by_velocity,
    filter_blobs_by_amplitude,
    filter_blobs_by_size,
    filter_blobs_by_detection_count,
    get_blob_statistics,
)
from .parse_dopplium_header import FileHeader

__version__ = "1.6.0"
__all__ = [
    "parse_dopplium",
    "parse_dopplium_raw",
    "parse_dopplium_rdch",
    "parse_dopplium_radarcube",
    "parse_dopplium_detections",
    "parse_dopplium_blobs",
    "parse_dopplium_tracks",
    "FileHeader",
    "BodyHeader",
    "FrameHeader",
    "RDChBodyHeader",
    "RadarCubeBodyHeader",
    "CPIHeader",
    "DetectionsBodyHeader",
    "DetectionsBatchHeader",
    "BlobsBodyHeader",
    "BlobsBatchHeader",
    "TracksBodyHeader",
    "TracksFrameHeader",
    "get_range_axis",
    "get_velocity_axis",
    "get_azimuth_axis",
    "get_elevation_axis",
    "get_processing_info",
    "has_known_angles",
    "uses_fft_for_angles",
    "filter_detections_by_range",
    "filter_detections_by_velocity",
    "filter_detections_by_amplitude",
    "get_detection_statistics",
    "filter_blobs_by_range",
    "filter_blobs_by_velocity",
    "filter_blobs_by_amplitude",
    "filter_blobs_by_size",
    "filter_blobs_by_detection_count",
    "get_blob_statistics",
    "filter_tracks_by_status",
    "filter_tracks_by_class",
    "filter_tracks_by_id",
    "filter_tracks_by_lifetime",
    "get_valid_coordinates",
    "cartesian_to_spherical",
    "spherical_to_cartesian",
    "get_track_statistics",
    "get_track_blob_statistics",
    "get_track_lifecycle_stats",
]

